### ISSUE TITLE
Alguns links

### ISSUE THREAD

**Issue by jackmakiyama** [Malagurti/patterns#1]
- [PHP: The Right Way](https://phptherightway.com/)
- [Bolt CMS](https://bolt.cm/)
- [PHP Standards Recommendations](https://www.php-fig.org/psr/)

**Comment by jackmakiyama** [comment]
Bora tentar levantar mais e depois alteramos o md.

**Comment by jackmakiyama** [comment]
- [Versionamento Semântico 2.0.0](https://semver.org/lang/pt-BR/)

**Comment by Malagurti** [comment]
blz
